# Generated by Django 3.0.7 on 2020-06-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registred_name', models.CharField(max_length=75)),
                ('brand_name', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.District')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('price', models.CharField(max_length=75)),
                ('maximum_user', models.CharField(max_length=75)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Panchayat')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=75)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Company_master')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.User_role')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Nation')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_from', models.DateTimeField()),
                ('license_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Pricing_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Role_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('is_allow', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.User_role')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.State'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.District')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Gender')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Nation')),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Panchayat')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.State')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('checkout', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('checkin', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Customer')),
            ],
        ),
    ]
