# Generated by Django 3.0.7 on 2020-06-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=10)),
                ('document_file', models.FileField(upload_to='customers/documents/')),
                ('document_type', models.CharField(max_length=10)),
                ('document_size', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default=0, max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default=0, max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmapp.Customer')),
            ],
        ),
    ]
